services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -inMemory"
